src/Sandbox/WebApp/Pages/Secured/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Secured
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Sandbox/WebApp/Pages/Secured/SpyAgency.cshtml.cs
using Backend.BLL;
using Backend.Models.SpyAgency;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Nager.Country;
using System.Collections.Generic;
using System.Linq;

namespace WebApp.Pages.Secured
{
    public class SpyAgencyModel : PageModel
    {
        private readonly SecretService _service;
        private readonly ILogger<SpyAgencyModel> _logger;
        public SpyAgencyModel(SecretService service, ILogger<SpyAgencyModel> logger)
        {
            _service = service;
            _logger = logger;
        }

        public List<Region> WorldRegions { get; set; }
        public List<SubRegion> SubRegions { get; set; }
        public List<ICountryInfo> Countries { get; set; }
        public Dictionary<string, List<Skill>> Agents { get; set; }
        public List<Assignment> Assignments
        { 
            get
            {
                var values = System.Enum.GetValues<Assignment>();
                return new List<Assignment>(values);
            }
        }
        public string WarningMessage { get; set; }
        [TempData]
        public string FeedbackMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public string RegionName { get; set; }
        [BindProperty(SupportsGet = true)]
        public SubRegion SubRegionName { get; set; }
        [BindProperty(SupportsGet =true)]
        public string CountryCode { get; set; }
        [BindProperty]
        public List<AgentAssignment> AgentAssignments { get; set; } = new List<AgentAssignment>(); // Ensure an empty list
        [BindProperty]
        public AgentAssignment NewlyAssignedAgent { get; set; }
        [BindProperty]
        public string AgentToRemove { get; set; }

        public void OnGet()
        {
            PopulateDropDownData();
            if(!string.IsNullOrEmpty(CountryCode))
                AgentAssignments = _service.LocateAgents(CountryCode);
        }

        private void PopulateDropDownData()
        {
            WorldRegions = _service.ListWorldRegions();
            SubRegions = _service.GetSubRegions(RegionName);
            Countries = SubRegionName == SubRegion.None ? new List<ICountryInfo>() : _service.GetCountries(SubRegionName);
            Agents = _service.AgentSkillSets;
        }

        public IActionResult OnPostChangeRegion()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = (string)null,
                CountryCode = (string)null
            });
        }

        public IActionResult OnPostChangeSubRegion()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = SubRegionName,
                CountryCode = (string)null
            });
        }

        public IActionResult OnPostChangeCountry()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = SubRegionName,
                CountryCode = CountryCode
            });
        }

        public void OnPostAddAgent()
        {
            // Minimal UI validation
            // 1. Preventing duplicates
            if (AgentAssignments.Any(agent => agent.CodeName == NewlyAssignedAgent.CodeName))
            {
                WarningMessage = "You cannot add duplicate agents";
                _logger.LogInformation(WarningMessage);
            }
            else
                // UI Processing
                AgentAssignments.Add(NewlyAssignedAgent);

            PopulateDropDownData();

        }

        public void OnPostRemoveAgent()
        {
            var agent = AgentAssignments.FirstOrDefault(person => person.CodeName == AgentToRemove);
            if (agent != null)
                AgentAssignments.Remove(agent);
            else
                WarningMessage = $"Hmm. For some reason, {AgentToRemove} is already gone.";

            PopulateDropDownData();
        }

        public IActionResult OnPostAssignAgents()
        {
            try
            {
                _service.DeployAgents(CountryCode, AgentAssignments);
                FeedbackMessage = $"Agents have been deployed to {CountryCode}";
                return RedirectToPage(new { RegionName = "", SubRegionName = "", CountryCode = "" });
            }
            catch (System.Exception ex)
            {
                WarningMessage = ex.Message;
                return Page(); // so that I preserve the user's inputs so that they can correct any input
            }
        }

        public IActionResult OnPostClearForm()
        {
            return RedirectToPage(new {RegionName = "", SubRegionName = "", CountryCode = ""});
        }
    }
}

src/Sandbox/WebApp/Pages/Secured/Training.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Secured
{
    public class TrainingModel : PageModel
    {
        

        public void OnGet()
        {
        }

        public void OnPost()
        {

        }
    }
}

src/Sandbox/WebApp/Pages/Secured/Index.cshtml
@page
@model WebApp.Pages.Secured.IndexModel
@{
}

<h1>Spyz-R-US<sub><i>eh</i></sub> <i class="las la-user-secret"></i></h1>

src/Sandbox/WebApp/Pages/Secured/SpyAgency.cshtml
@page "{RegionName?}/{SubRegionName?}/{CountryCode?}"
@using Humanizer
@model WebApp.Pages.Secured.SpyAgencyModel
@{
}

<style>
    section {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 5px;
    }

    [type=submit].danger {
        color: var(--danger-text-color);
        background-color: var(--danger-hover-color);
        border-color: transparent;
    }
    [type=submit].danger:hover {
        background-color: var(--danger-hover-color);
        border-color: var(--danger-color);
    }
    tbody > tr.hidden {
        display: none;
    }
    tbody > tr.selected {
        background-color: azure;
    }
    .skills td {
        padding-left: 1.7rem;
    }
    blockquote.warning {
        border-color: var(--danger-color);
    }
    blockquote.feedback {
        border-color: var(--success-color);
    }
</style>

<h1>Spy Agency Deployment Centre <i class="las la-user-secret"></i></h1>

<section>
    <form method="post" asp-page-handler="ChangeRegion">
        <label>
            Region
            <select asp-for="RegionName"
                    onchange="this.form.submit()">
                <option value="">Region</option>
                @foreach (var place in Model.WorldRegions)
                {
                    <option value="@place">@place</option>
                }
            </select>
        </label>
    </form>
    <form method="post" asp-page-handler="ChangeSubRegion">
        <label>
            Sub-Region
            <select asp-for="SubRegionName"
                    onchange="this.form.submit()">
                <option value="">Sub-Region</option>
                @foreach (var place in Model.SubRegions)
                {
                    <option value="@place">@place</option>
                }
            </select>
        </label>
    </form>
    <form method="post" asp-page-handler="ChangeCountry">
        <label>
            Country
            <select asp-for="CountryCode"
                    onchange="this.form.submit()">
                <option value="">Country</option>
                @foreach (var place in Model.Countries)
                {
                    <option value="@place.Alpha3Code">@place.CommonName</option>
                }
            </select>
        </label>
    </form>
</section>

<hr />

@if (!string.IsNullOrEmpty(Model.CountryCode))
{
    <h2>Agents</h2>

    if (!string.IsNullOrEmpty(Model.WarningMessage))
    {
        <blockquote class="warning">@Model.WarningMessage</blockquote>
    }
    if (!string.IsNullOrEmpty(Model.FeedbackMessage))
    {
        <blockquote class="feedback">@Model.WarningMessage</blockquote>
    }

    <script>
        const toggleDetails = function(el) {
            console.log(el);
            if(el.classList.contains('la-caret-right')){
                el.classList.remove('la-caret-right');
                el.classList.add('la-caret-down');
                el.parentElement.parentElement.classList.add('selected');
                el.parentElement.parentElement.nextElementSibling.classList.remove('hidden');
            } else {
                el.classList.add('la-caret-right');
                el.classList.remove('la-caret-down');
                el.parentElement.parentElement.classList.remove('selected');
                el.parentElement.parentElement.nextElementSibling.classList.add('hidden');
            }
        }
    </script>
    <form method="POST">
        <table>
            <thead>
                <tr>
                    <th>
                        <input name="NewlyAssignedAgent.CodeName" placeholder="Code Name" list="agents" />
                        <datalist id="agents">
                            @foreach(var agent in Model.Agents)
                            {
                                <option value="@agent.Key">@agent.Key - (@agent.Value.Count skills)</option>
                            }
                        </datalist>
                    </th>
                    <th>
                        <select name="NewlyAssignedAgent.LocalAssignment">
                            @foreach (var item in Model.Assignments)
                            {
                                <option value="@item">@item</option>
                            }
                        </select>
                    </th>
                    <th>
                        <input name="NewlyAssignedAgent.PrimaryMission" placeholder="Primary Mission" />
                    </th>
                    <th>
                        <button type="submit" asp-page-handler="AddAgent" title="Add Agent"><i class="las la-plus"></i></button>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AgentAssignments)
                {
                    <tr>
                        <td>
                            <i class="las la-caret-right" onclick="toggleDetails(this)"></i>
                            @item.CodeName
                            <input type="hidden"
                           name="AgentAssignments.Index"
                           value="@item.CodeName" />
                            <input type="hidden"
                           name="AgentAssignments[@item.CodeName].CodeName"
                           value="@item.CodeName" />
                        </td>
                        <td>
                            @item.LocalAssignment
                            <input type="hidden"
                           name="AgentAssignments[@item.CodeName].LocalAssignment"
                           value="@item.LocalAssignment" />
                        </td>
                        <td>
                            @item.PrimaryMission
                            <input type="hidden"
                           name="AgentAssignments[@item.CodeName].PrimaryMission"
                           value="@item.PrimaryMission" />
                        </td>
                        <td>
                            <button type="submit" name="AgentToRemove" value="@item.CodeName"
                                    title="Remove Agent" class="danger"
                                    asp-page-handler="RemoveAgent"><i class="las la-times"></i></button>
                        </td>
                    </tr>
                    <tr class="skills selected hidden">
                        <td colspan="4">
                            @if(Model.Agents.ContainsKey(item.CodeName)){
                                string skills = "";
                                var lastSkill = Model.Agents[item.CodeName].Last();
                                foreach(var skill in Model.Agents[item.CodeName])
                                {
                                    skills += skill.Humanize();
                                    if(skill != lastSkill)
                                    {
                                        skills += ", ";
                                    }
                                }
                                @: Trained in: 
                                <b>@skills</b>
                            }
                            else
                            {
                               <i>No Listed Skills</i>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <button type="submit" asp-page-handler="AssignAgents">Assign</button>
        <button type="submit" asp-page-handler="ClearForm">Clear Form</button>
    </form>
}

src/Sandbox/WebApp/Pages/Secured/Training.cshtml
@page
@model WebApp.Pages.Secured.TrainingModel
@{
}