src/006/WestWind-CRUD/WebApp/Pages/OrderDetailsEditor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WestWind.BLL;
using WestWind.Entities;

namespace WebApp.Pages
{
    public class OrderDetailsEditorModel : PageModel
    {
        #region Constructor & DI
        private readonly TableMaintenanceServices _services;
        public OrderDetailsEditorModel(TableMaintenanceServices services)
        {
            _services = services ?? throw new ArgumentNullException();
        }
        #endregion

        #region Properties
        [BindProperty(SupportsGet = true)]
        public int? OrderDetailId { get; set; }
        [TempData]
        public string _SelectedCustomer { get; set; }
        [TempData]
        public string _PartialProductName { get; set; }
        [TempData]
        public string PostRedirectFeedback { get; set; }
        public string ErrorMessage { get; set; }


        [BindProperty]
        public OrderDetail OrderItem { get; set; }
        [BindProperty]
        public string SelectedCustomer { get; set; }
        [BindProperty]
        public string PartialProductName { get; set; }
        [BindProperty]
        public int SelectedOrder { get; set; }

        public List<SelectListItem> CustomerOrders { get; set; } = new();
        public List<SelectListItem> Customers { get; set; }
        public List<SelectListItem> Products { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
        #endregion

        #region Request Handlers
        #region GET Request
        public void OnGet()
        {
            if (OrderDetailId.HasValue)
            {
                // An existing order detail item
                OrderItem = _services.GetOrderDetail(OrderDetailId.Value);
            }
            else
            {
                // Searching for existing or adding a new item
                SelectedCustomer = _SelectedCustomer;
                PartialProductName = _PartialProductName;
            }
            PopulateSelectionLists();
        }
        #endregion

        #region POST Requests
        public IActionResult OnPost()
        {
            return RedirectToPage(new { OrderDetailId = OrderDetailId });
        }

        public IActionResult OnPostNarrowResults()
        {
            _SelectedCustomer = SelectedCustomer;
            _PartialProductName = PartialProductName;
            return RedirectToPage();
        }

        public IActionResult OnPostAdd()
        {
            try
            {
                if (!OrderDetailId.HasValue)
                {
                    _services.AddOrderDetail(OrderItem);
                    PostRedirectFeedback = "Product order details have been updated.";
                    return RedirectToPage(new { OrderDetailId = OrderItem.OrderDetailId });
                }
                else
                {
                    ErrorMessage = "You should clear the form before trying to add a new order detail item.";
                    PopulateSelectionLists();
                    return Page();
                }
            }
            catch (Exception ex)
            {
                SetErrorMessage(ex);
                PopulateSelectionLists();
                return Page(); // Return the page as the POST result - This will preserve any user inputs
            }
        }

        public IActionResult OnPostUpdate()
        {
            try
            {
                if (OrderDetailId.HasValue)
                {
                    OrderItem.OrderDetailId = OrderDetailId.Value;
                    _services.UpdateOrderDetail(OrderItem);
                    PostRedirectFeedback = "Product order details have been updated.";
                    return RedirectToPage(new { OrderDetailId = OrderDetailId });
                }
                else
                {
                    ErrorMessage = "You can only update an existing item on the order.";
                    PopulateSelectionLists();
                    return Page();
                }
            }
            catch (Exception ex)
            {
                SetErrorMessage(ex);
                PopulateSelectionLists();
                return Page(); // Return the page as the POST result - This will preserve any user inputs
            }
        }

        public IActionResult OnPostDelete()
        {
            try
            {
                if (OrderDetailId.HasValue)
                {
                    OrderItem.OrderDetailId = OrderDetailId.Value;
                    _services.DeleteOrderDetail(OrderItem);
                    PostRedirectFeedback = "Product has been removed from the order.";
                    return RedirectToPage(new { OrderDetailId = (int?)null });
                }
                else
                {
                    ErrorMessage = "You can only delete an existing item on the order.";
                    PopulateSelectionLists();
                    return Page();
                }
            }
            catch (Exception ex)
            {
                SetErrorMessage(ex);
                PopulateSelectionLists();
                return Page(); // Return the page as the POST result - This will preserve any user inputs
            }
        }

        public IActionResult OnPostClearForm()
        {
            return RedirectToPage( new { OrderDetailId = (int?)null });
        }
        #endregion
        #endregion

        #region Private helper methods
        private void SetErrorMessage(Exception ex)
        {
            // Start with the assumption that the given exception is the root of the problem
            Exception rootCause = ex;
            // Loop to "drill-down" to what the original cause of the problem is
            while (rootCause.InnerException != null)
                rootCause = rootCause.InnerException;

            ErrorMessage = rootCause.Message;
        }

        private void PopulateSelectionLists()
        {
            Customers = _services
                .ListAllCustomers()
                .Select(x => new SelectListItem($"{x.CompanyName}", x.CustomerId))
                .ToList();
            CustomerOrders = _services
                .ListOpenOrders(SelectedCustomer)
                .Select(x => new SelectListItem($"{x.OrderId} {(x.OrderDate.HasValue ? x.OrderDate.Value.ToShortDateString() : "-no date-")}", x.OrderId.ToString()))
                .ToList();
            Products = _services
                .ListMatchingProducts(PartialProductName)
                .Select(x => new SelectListItem(x.ProductName, x.ProductId.ToString()))
                .ToList();
            OrderDetails = _services
                .ListOrderDetails(SelectedCustomer, PartialProductName);
        }
        #endregion
    }
}

src/006/WestWind-CRUD/WebApp/Pages/OrderEditor.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using WestWind.BLL;
using WestWind.Entities;

namespace WebApp.Pages
{
    public class OrderEditorModel : PageModel
    {
        #region Constructor + DI Properties
        private readonly TableMaintenanceServices _services;
        public OrderEditorModel(TableMaintenanceServices services)
        {
            _services = services ?? throw new ArgumentNullException();
        }
        #endregion

        #region Model Properties
        [BindProperty]
        public string SelectedCustomer { get; set; }
        [BindProperty]
        public int SelectedOrder { get; set; }
        [BindProperty]
        public Order CurrentOrder { get; set; }
        public List<SelectListItem> OpenOrders { get; set; } = new();
        public List<SelectListItem> Employees { get; set; }
        public List<SelectListItem> Customers { get; set; }
        public List<SelectListItem> Addresses { get; set; } = new();
        public string ErrorMessage { get; set; }
        [TempData]
        public string Feedback { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? OrderId { get; set; }
        [BindProperty]
        public string PartialAddress { get; set; }
        #endregion

        #region Request Handlers
        #region GET Request
        public void OnGet(int? id)
        {
            PopulateDropDowns();
            if (id.HasValue)
            {
                try
                {
                    CurrentOrder = _services.GetOrder(id.Value);
                    OrderId = CurrentOrder.OrderId;
                }
                catch (Exception ex)
                {
                    // Start with the assumption that the given exception is the root of the problem
                    Exception rootCause = ex;
                    // Loop to "drill-down" to what the original cause of the problem is
                    while (rootCause.InnerException != null)
                        rootCause = rootCause.InnerException;

                    ErrorMessage = rootCause.Message;
                }
            }
        }
        #endregion

        #region POST Requests
        public void OnPostSearchCustomerOrders()
        {
            PopulateDropDowns();
            OpenOrders = _services
                .ListOpenOrders(SelectedCustomer)
                .Select(x => new SelectListItem($"{x.OrderId} {(x.OrderDate.HasValue ? x.OrderDate.Value.ToShortDateString() : "-no date-")}", x.OrderId.ToString()))
                .ToList();
        }

        public IActionResult OnPostLookupOrder()
        {
            if (SelectedOrder > 0)
            {
                Feedback = "Order Found";
                return RedirectToPage(new { id = SelectedOrder });
            }
            else
            {
                Feedback = "Select an order before looking it up";
                return Page();
            }
        }

        public void OnPostSearchAddress()
        {
            PopulateDropDowns();
            Addresses = _services
                .ListAddresses(PartialAddress)
                .Select(x => new SelectListItem($"{x.Address1} {x.City}", x.AddressId.ToString()))
                .ToList();
        }

        public IActionResult OnPostClearForm()
        {
            return RedirectToPage(new { id = (int?)null });
        }

        public IActionResult OnPostAdd()
        {
            if (ModelState.IsValid) // recheck the validation based on the asp-validation-for
            {
                try
                {
                    _services.AddOrder(CurrentOrder); // Calling the ProductInventoryService.AddProduct method
                                                      // Use the POST-Redirect-GET pattern to prevent inadvertent resubmissions of POST requests
                    Feedback = "New customer order generated."; // Set the value of a [TempData] property for messages temporarily stored in cookies for redirect.
                    return RedirectToPage(new { id = CurrentOrder.OrderId });
                }
                catch (Exception ex)
                {
                    // Start with the assumption that the given exception is the root of the problem
                    Exception rootCause = ex;
                    // Loop to "drill-down" to what the original cause of the problem is
                    while (rootCause.InnerException != null)
                        rootCause = rootCause.InnerException;

                    ErrorMessage = rootCause.Message;
                    PopulateDropDowns();
                    return Page(); // Return the page as the POST result - This will preserve any user inputs
                }
            }
            else
            {
                ErrorMessage = $"There were {ModelState.ErrorCount} problems with your form submission.";
                foreach (var item in ModelState)
                {
                    foreach (var problem in item.Value.Errors)
                    {
                        ErrorMessage += $" Problem with {item.Key}: {problem.ErrorMessage}";
                    }
                }
                PopulateDropDowns();
                return Page();
            }
        }

        public IActionResult OnPostUpdate()
        {
            if (OrderId.HasValue && ModelState.IsValid)
            {
                try
                {
                    CurrentOrder.OrderId = OrderId.Value;
                    _services.UpdateOrder(CurrentOrder);
                    // Redirect to GET request since everything worked out OK
                    Feedback = "Order Updated.";
                    return RedirectToPage(new { id = CurrentOrder.OrderId });
                }
                catch (Exception ex)
                {
                    // Start with the assumption that the given exception is the root of the problem
                    Exception rootCause = ex;
                    // Loop to "drill-down" to what the original cause of the problem is
                    while (rootCause.InnerException != null)
                        rootCause = rootCause.InnerException;

                    ErrorMessage = rootCause.Message;
                    PopulateDropDowns();
                    return Page(); // Return the page as the POST result - This will preserve any user inputs
                }
            }
            else
            {
                ErrorMessage = "Invalid Order Information - Unable to update this order";
                PopulateDropDowns();
                return Page();
            }
        }

        public IActionResult OnPostDelete()
        {
            try
            {
                if (OrderId.HasValue)
                {
                    CurrentOrder.OrderId = OrderId.Value;
                    _services.DeleteOrder(CurrentOrder);
                    Feedback = "Customer Order has been removed from the database.";
                    return RedirectToPage(new { id = (int?)null }); // I need to remember to be explicit about having a "blank" product id
                }
                else
                {
                    ErrorMessage = "You can only delete an existing order.";
                    PopulateDropDowns();
                    return Page();
                }
            }
            catch (Exception ex)
            {
                // Start with the assumption that the given exception is the root of the problem
                Exception rootCause = ex;
                // Loop to "drill-down" to what the original cause of the problem is
                while (rootCause.InnerException != null)
                    rootCause = rootCause.InnerException;

                ErrorMessage = rootCause.Message;
                PopulateDropDowns();
                return Page(); // Return the page as the POST result - This will preserve any user inputs
            }
        }
        #endregion
        #endregion

        #region Private helper methods
        private void PopulateDropDowns()
        {
            Employees = _services
                .ListAllEmployees()
                .Select(x => new SelectListItem($"{x.FirstName} {x.LastName}", x.EmployeeId.ToString()))
                .ToList();

            Customers = _services
                .ListAllCustomers()
                .Select(x => new SelectListItem(x.CompanyName, x.CustomerId))
                .ToList();

        }

        #endregion
    }
}

src/006/WestWind-CRUD/WebApp/Pages/ViewProductCatalog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestWind.BLL;
using WestWind.Collections;
using WestWind.Entities;
using WestWind.Helpers;

namespace WebApp.Pages
{
    public class ViewProductCatalogModel : PageModel
    {
        private readonly TableMaintenanceServices _service;
        public ViewProductCatalogModel(TableMaintenanceServices service)
        {
            _service = service ?? throw new ArgumentNullException();
        }

        public PartialList<Product> Catalog { get; set; }
        public Paginator Paging { get; set; }
        [BindProperty]
        public string PartialName { get; set; }

        public void OnGet(int? currentPage, string partialName)
        {
            PartialName = partialName; // Capturing the GET request value to store on the bound property
            int pageNumber = currentPage.HasValue ? currentPage.Value : 1;
            int pageIndex = pageNumber - 1; //Zero-based for the calulation of skip
            int pageSize = 10;
            int skip = pageIndex * pageSize;
            Catalog = _service.GetProducts(partialName, skip, pageSize);
            PageState current = new(pageNumber, pageSize);
            Paging = new(Catalog.TotalCount, current);
        }
    }
}

src/006/WestWind-CRUD/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <h1>Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

src/006/WestWind-CRUD/WebApp/Pages/OrderDetailsEditor.cshtml
@page "{OrderDetailId?}"
@model OrderDetailsEditorModel
@{
}

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

<h1>Order Details Editor</h1>
@if (!Model.OrderDetailId.HasValue)
{
    <h2>Search for Order Detail</h2>
    <style>
        form > fieldset label:not(:first-child) {
            margin-top: 0;
        }

        form > fieldset, section {
            display: grid;
            grid-template-columns: 2fr 2fr 4fr;
        }

            section > blockquote {
                font-weight: bold;
            }

        blockquote {
            margin: 0;
        }
    </style>
    <form method="post">
        <fieldset>
            <label>
                Customer Selection
                <select asp-items="Model.Customers" asp-for="SelectedCustomer">
                    <option value=''>[Select a Customer]</option>
                </select>
            </label>
            <label>
                Partial Product Name
                <input type='text' asp-for='PartialProductName' />
            </label>
            <div>
                Begin by identifying the customer and the product.
                <button type="submit" asp-page-handler="NarrowResults">Narrow Results</button>
            </div>
        </fieldset>
    </form>
    @if (!Model.OrderDetails.Any())
    {
        <blockquote>No matching order details for the given customer/product.</blockquote>
    }
    else
    {
        <section>
            <blockquote>Order ID</blockquote>
            <blockquote>Product Detail</blockquote>
            <blockquote>Action</blockquote>
            @foreach (var detail in Model.OrderDetails)
            {
                <div>@detail.OrderId</div>
                <div>@detail.Product.ProductName (qty: @detail.Quantity)</div>
                <div>
                    <form method="post" asp-page-handler="SelectOrderDetail">
                        <input type="hidden" asp-for="OrderDetailId" value="@detail.OrderDetailId" />
                        <button type="submit">Edit this item</button>
                    </form>
                </div>
            }
        </section>
    }
    <hr>
}

<h2>Order Detail Item</h2>

<p style="color:blue; font-weight: bold;">@Model.PostRedirectFeedback</p>

@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <p style="color:red; font-weight: bold;">@Model.ErrorMessage</p>
}

<form method="POST">
    @if (Model.OrderDetailId.HasValue)
    {
        <button type="submit" asp-page-handler="Add" disabled>Add Order Detail</button>
        <button type="submit" asp-page-handler="Update">Update Order Detail</button>
        <button type="submit" asp-page-handler="Delete" onclick="return confirm('Are you sure you want to delete this order?')">Delete Order Detail</button>
        <button type="submit" asp-page-handler="ClearForm" onclick="return confirm('Are you sure you want to clear this form?')">Clear Form</button>
    }
    else
    {
        <button type="submit" asp-page-handler="Add">Add Order Detail</button>
        <button type="submit" asp-page-handler="Update" disabled>Update Order Detail</button>
        <button type="submit" asp-page-handler="Delete" disabled onclick="return confirm('Are you sure you want to delete this order?')">Delete Order Detail</button>
    }

    <br>
    <label>
        Order Detail ID <i>(automatically generated)</i>
        <input type='number' asp-for='OrderDetailId' disabled />
    </label>

    <label>
        Order
        <span asp-validation-for="OrderItem.OrderId" style="color:red;"></span>
        <input type='text' asp-for='OrderItem.OrderId' list="customerOrders" />
        <datalist id='customerOrders'>
            @foreach (var item in Model.CustomerOrders)
            {
                <option value='@item.Value'>@item.Text</option>
            }
        </datalist>
    </label>

    <label>
        Product
        <span asp-validation-for="OrderItem.ProductId" style="color:red;"></span>
        <input type='text' asp-for='OrderItem.ProductId' list="products" />
        <datalist id='products'>
            @foreach (var item in Model.Products)
            {
                <option value='@item.Value'>@item.Text</option>
            }
        </datalist>
    </label>

    <label>
        Unit Price
        <span asp-validation-for="OrderItem.UnitPrice" style="color:red;"></span>
        <input type='number' step=".0001" asp-for='OrderItem.UnitPrice' />
    </label>

    <label>
        Quantity
        <span asp-validation-for="OrderItem.Quantity" style="color:red;"></span>
        <input type='number' step="1" asp-for='OrderItem.Quantity' />
    </label>

    <label>
        Discount
        <span asp-validation-for="OrderItem.Discount" style="color:red;"></span>
        <input type='number' step=".01" asp-for='OrderItem.Discount' />
    </label>
</form>

src/006/WestWind-CRUD/WebApp/Pages/OrderEditor.cshtml
@page "{id?}"
@model OrderEditorModel
@{
}
<style>
    main {
        column-count: 2;
        column-rule-color: black;
        column-rule-style: solid;
        column-rule-width: thin;
    }

        main > h1 {
            column-span: all;
        }

        main > section:first-of-type {
            break-after: column;
        }
</style>
<h1>Order Editor</h1>

<section>
    <h2>Order Information</h2>

    <p style="color:blue; font-weight: bold;">@Model.Feedback</p>

    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <p style="color:red; font-weight: bold;">@Model.ErrorMessage</p>
    }

    <form method="POST">
        @if (Model.CurrentOrder != null && Model.CurrentOrder.OrderId != 0)
        {
            <button type="submit" asp-page-handler="Add" disabled>Add Order</button>
            <button type="submit" asp-page-handler="Update">Update Order</button>
            <button type="submit" asp-page-handler="Delete" onclick="return confirm('Are you sure you want to delete this order?')">Delete Order</button>
            <button type="submit" asp-page-handler="ClearForm" onclick="return confirm('Are you sure you want to clear this form?')">Clear Form</button>
        }
        else
        {
            <button type="submit" asp-page-handler="Add">Add Order</button>
            <button type="submit" asp-page-handler="Update" disabled>Update Order</button>
            <button type="submit" asp-page-handler="Delete" disabled>Delete Order</button>
        }

        <div asp-validation-summary="All" style="color:red;">
            <span>Please correct the following errors</span>
        </div>
        <style>
            .validation-summary-valid span {
                display: none;
            }
        </style>

        <label>
            Order ID <i>(automatically generated)</i>
            <input type='number' asp-for='OrderId' disabled />
        </label>

        <label>
            Sales Rep
            <select asp-items='Model.Employees' asp-for='CurrentOrder.SalesRepId'>
                <option value=''>[Select an Employee]</option>
            </select>
        </label>

        <label>
            Customer
            <span asp-validation-for="CurrentOrder.CustomerId" style="color:red;"></span>
            <select asp-items='Model.Customers' asp-for='CurrentOrder.CustomerId' required>
                <option value=''>[Select a Customer]</option>
            </select>
        </label>

        <label>
            Order Date
            <input type='Date' asp-for='CurrentOrder.OrderDate' />
        </label>

        <label>
            Required Date
            <input type='Date' asp-for='CurrentOrder.RequiredDate' />
        </label>

        <label>
            Payment Due Date
            <input type='Date' asp-for='CurrentOrder.PaymentDueDate' />
        </label>

        <label>
            Freight
            <input type='number' step=".01" asp-for='CurrentOrder.Freight' />
        </label>

        <label>
            Shipped
            <label>
                <input type='checkbox' asp-for='CurrentOrder.Shipped' />
                Products have been delivered
            </label>
        </label>

        <label>
            Ship Name
            <input type='text' asp-for='CurrentOrder.ShipName' />
        </label>

        <label>
            Ship-To Address
            <datalist id="MatchingAddresses">
                @foreach (var match in Model.Addresses)
                {
                    <option value="@match.Value">@match.Text</option>
                }
            </datalist>
            <input type="number" asp-for="CurrentOrder.ShipAddressId" list="MatchingAddresses" placeholder="ID #" />
        </label>
        <dialog open="true" title="Search a partial address to get a data list of IDs">
            <input type="search" asp-for='PartialAddress' placeholder="Partial Address" />
            <button type="submit" formnovalidate asp-page-handler="SearchAddress"><i class="fas fa-search"></i></button>
        </dialog>

        <label>
            Comments
            <textarea asp-for='CurrentOrder.Comments'></textarea>
        </label>
    </form>
</section>

<section>
    <h2>Search for Order</h2>

    <form method="POST">
        <label>
            Customer
            <select asp-items='Model.Customers' asp-for='SelectedCustomer'>
                <option value=''>[Select a Customer]</option>
            </select>
            <button type='submit' asp-page-handler='SearchCustomerOrders'>Search Customer Orders</button>
        </label>
        <label>
            Customer Orders
            <select asp-items='Model.OpenOrders' asp-for='SelectedOrder'>
                <option value=''>[Select an order]</option>
            </select>
            <button type='submit' asp-page-handler='LookupOrder'>Lookup Order</button>
        </label>
    </form>
</section>

src/006/WestWind-CRUD/WebApp/Pages/ProductEditor.cshtml
@page "{id?}"
@model WebApp.Pages.ProductEditorModel
@{
}

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

<h1>Product Editor</h1>

<p style="color:blue; font-weight: bold;">@Model.FeedbackMessage</p>

@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <p style="color:red; font-weight: bold;">@Model.ErrorMessage</p>
}

<form method="post">
    <button type="submit" asp-page-handler="Add">Add Product</button>
    @if (Model.ProductItem != null)
    {
        <button type="submit" asp-page-handler="Update">Update Product</button>
        <button type="submit" asp-page-handler="Delete" onclick="return confirm('Are you sure you want to delete this product?')">Delete Product</button>
    }
    else
    {
        <button type="submit" asp-page-handler="Update" disabled>Update Product</button>
        <button type="submit" asp-page-handler="Delete" disabled>Delete Product</button>
    }
    <button type="submit" formnovalidate asp-page-handler="Cancel">Cancel</button>

    <div asp-validation-summary="All"  style="color:red;">
        <span>Please correct the following errors</span>
    </div>
    <style>
        .validation-summary-valid span {
            display: none;
        }
    </style>

    <label>
        Product ID
        <input type="number" asp-for="Id" disabled />
    </label>

    <label>
        Product Name
        <span asp-validation-for="ProductItem.ProductName" style="color:red;"></span>
        <input type="text" asp-for="ProductItem.ProductName" />
    </label>

    <label>
        Supplier
        <span asp-validation-for="ProductItem.SupplierId" style="color:red;"></span>
        <select asp-items="Model.Suppliers" asp-for="ProductItem.SupplierId">
            <option value="">[Pick a Supplier]</option>
        </select>
    </label>

    <label>
        Category
        <span asp-validation-for="ProductItem.CategoryId" style="color:red;"></span>
        <select asp-for="ProductItem.CategoryId">
            <option value="">[Pick a Category]</option>
            @{
                foreach (var item in Model.Categories)
                {
                    <option value="@item.CategoryId">@item.Description</option>
                }
            }
        </select>
    </label>

    <label>
        Quantity per Unit
        <span asp-validation-for="ProductItem.QuantityPerUnit" style="color:red;"></span>
        <input type="text" asp-for="ProductItem.QuantityPerUnit" />
    </label>

    <label>
        Unit Price
        <span asp-validation-for="ProductItem.UnitPrice" style="color:red;"></span>
        <input type="number" step=".0001" asp-for="ProductItem.UnitPrice" />
    </label>

    <label>
        Minimum Order Quantity
        <span asp-validation-for="ProductItem.MinimumOrderQuantity" style="color:red;"></span>
        <input type="number" step="1" asp-for="ProductItem.MinimumOrderQuantity" />
    </label>

    <label>
        Units on Order
        <span asp-validation-for="ProductItem.UnitsOnOrder" style="color:red;"></span>
        <input type="number" step="1" asp-for="ProductItem.UnitsOnOrder" />
    </label>

    <label>
        Discontinued
        <label><input type="checkbox" asp-for="ProductItem.Discontinued" /> Is Discontinued</label>
    </label>
</form>