src/Sandbox/WebApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Backend.BLL;
using Backend.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class AboutModel : PageModel
    {
        private readonly AboutService _service;
        private readonly IWebHostEnvironment _environment;
        public AboutModel(AboutService service, IWebHostEnvironment env)
        {
            _service = service;
            _environment = env;
        }

        public DatabaseVersion DatabaseVersion { get; set; }
        public DatabaseInfo DatabaseInfo { get; set; }
        public string WebRootPath
        { get { return _environment.WebRootPath; } }
        public string ApplicationPath
        { get { return _environment.ContentRootPath; } }

        public void OnGet()
        {
            DatabaseVersion = _service.GetDatabaseVersion();
            DatabaseInfo = _service.GetDatabaseInformation();
        }
    }
}

src/Sandbox/WebApp/Pages/AdHoc.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Backend.BLL;
using Backend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class AdHocModel : PageModel
    {
        #region Constructor and Depedencies
        private readonly CapstoneService _service;

        public AdHocModel(CapstoneService service)
        {
            _service = service;
        }
        #endregion

        #region Properties
        public List<CapstoneClient> Companies { get; set; }


        [BindProperty(SupportsGet = true)]
        public int? ClientId { get; set; }
        [BindProperty]
        public CapstoneClient Client { get; set; }
        #endregion

        #region Request Handlers
        public void OnGet()
        {
            Companies = _service.ListClients();
            if (ClientId.HasValue)
                Client = _service.LookupClient(ClientId.Value);
        }

        public void OnPostAdd()
        {
            Companies = _service.ListClients();
            // TODO: something
            // pretend I have updated....
            Client.Id = 345;
        }
        #endregion
    }
}

src/Sandbox/WebApp/Pages/Admin/ManageCapstoneStudents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Backend.BLL;
using Backend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Admin
{
    public class ManageCapstoneStudentsModel : PageModel
    {
        #region Constructor and Depedencies
        private readonly CapstoneService _service;
        public ManageCapstoneStudentsModel(CapstoneService service)
        {
            _service = service;
        }
        #endregion

        public List<StudentName> AllStudents { get; set; }
        public string ErrorMessage { get; set; }

        [BindProperty(SupportsGet = true)] // for POST and GET Requests (GET through the routing parameter)
        public int? SelectedStudent { get; set; }
        [BindProperty] // for POST Requests
        public Student CurrentStudent { get; set; }
        
        [TempData]
        public string FeedbackMessage { get; set; }

        public void OnGet()
        {
            AllStudents = _service.ListCapstoneStudents();
            if(SelectedStudent.HasValue)
            {
                // Lookup and display the student information.
                CurrentStudent = _service.LookupStudent(SelectedStudent.Value);
            }
        }

        public IActionResult OnPost()
        {
            return RedirectToPage(new { SelectedStudent });
        }

        public IActionResult OnPostAdd()
        {
            try
            {
                // The response to the browser is a Post-Redirect-Get pattern
                int newId = _service.AddStudent(CurrentStudent);
                FeedbackMessage = $"Successfully added {CurrentStudent.FirstName} to the list of Capstone Students.";
                return RedirectToPage(new { SelectedStudent = newId });
            }
            catch (Exception ex)
            {
                // The response to the browser is the result of this POST processing
                Exception innermost = ex;
                while (innermost.InnerException != null)
                    innermost = innermost.InnerException;
                ErrorMessage = innermost.Message;
                AllStudents = _service.ListCapstoneStudents();
                return Page();
            }
        }

        public IActionResult OnPostUpdate()
        {
            try
            {
                _service.UpdateStudent(SelectedStudent.Value, CurrentStudent);
                FeedbackMessage = $"Successfully updated information for {CurrentStudent.FirstName}.";
                return RedirectToPage(new { SelectedStudent = SelectedStudent });
            }
            catch (Exception ex)
            {
                // The response to the browser is the result of this POST processing
                Exception innermost = ex;
                while (innermost.InnerException != null)
                    innermost = innermost.InnerException;
                ErrorMessage = innermost.Message;
                AllStudents = _service.ListCapstoneStudents();
                return Page();
            }
        }

        public IActionResult OnPostDelete()
        {
            try
            {
                _service.DeleteStudent(SelectedStudent.Value);
                FeedbackMessage = $"Successfully removed {CurrentStudent.FirstName} {CurrentStudent.LastName} ({CurrentStudent.ID}).";
                return RedirectToPage(new { SelectedStudent = (int?)null });
            }
            catch (Exception ex)
            {
                // The response to the browser is the result of this POST processing
                Exception innermost = ex;
                while (innermost.InnerException != null)
                    innermost = innermost.InnerException;
                ErrorMessage = innermost.Message;
                AllStudents = _service.ListCapstoneStudents();
                return Page();
            }
        }

        public IActionResult OnPostClear()
        {
            return RedirectToPage(new { SelectedStudent = (int?)null });
        }
    }
}

src/Sandbox/WebApp/Pages/ColorPalletPicker.cshtml.cs
using Backend.BLL;
using Backend.Models.Colors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;

namespace WebApp.Pages
{
    public class ColorPalletPickerModel : PageModel
    {
        private readonly AboutService _service;

        public ColorPalletPickerModel(AboutService service)
        {
            _service = service;
        }

        [BindProperty]
        public List<NamedColor> AvailableColors { get; set; }
        [BindProperty]
        public List<NamedColor> ColorPallete { get; set; } = new();
        [BindProperty]
        public string SelectedColor {get;set;}

        public void OnGet()
        {
            AvailableColors = _service.ListHTMLColors();
        }

        public void OnPostAddItem()
        {
            var found = AvailableColors.SingleOrDefault(x => x.Name == SelectedColor);
            if (found != null)
            {
                AvailableColors.Remove(found);
                ColorPallete.Add(found);
            }
        }

        public void OnPostRemoveItem()
        {
            var found = ColorPallete.SingleOrDefault(x => x.Name == SelectedColor);
            if (found != null)
            {
                AvailableColors.Add(found);
                ColorPallete.Remove(found);
            }
        }
    }
}

src/Sandbox/WebApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO; // The namespace for everything File I/O

namespace WebApp.Pages
{
    public class ContactModel : PageModel
    {
        private readonly IWebHostEnvironment _environment;
        public ContactModel(IWebHostEnvironment env)
        {
            _environment = env;
        }

        [BindProperty] // This attribute allows our Razor Page to "assign" the form item to this property
        public IFormFile ApplicantResume { get; set; }
        public string ApplicationPath
        { get { return _environment.ContentRootPath; } }

        public void OnGet()
        {
        }

        public void OnPost()
        {
            // Save this file to my application (somewhere) - Confidential
            string folderPath = Path.Combine(ApplicationPath, "Confidential");
            if (!Directory.Exists(folderPath))
                Directory.CreateDirectory(folderPath);

            // File name, I'll use the same name that was given by the user
            // CAUTION - It's kinda dangerous to trust the file name given by the browser
            string fileName = Path.Combine(folderPath, ApplicantResume.FileName);
            if (!System.IO.File.Exists(fileName)) 
            {
                using(var stream = System.IO.File.Create(fileName))
                {
                    ApplicantResume.CopyTo(stream);
                }
            }
        }
    }
}

src/Sandbox/WebApp/Pages/JobCandidates.cshtml.cs
using Backend.BLL;
using Backend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace WebApp.Pages
{
    public class JobCandidatesModel : PageModel
    {
        private readonly RandomDataService _service;

        public JobCandidatesModel(RandomDataService service)
        {
            _service = service;
        }


        public List<string> Openings { get; set; } // for the drop-down
        [BindProperty]
        public string SelectedOpening { get; set; } // for the selected item in the drop-down

        // The following two List<T> will be both displayed and gathered in an HTML table
        [BindProperty]
        public List<Applicant> Applicants { get; set; }
        [BindProperty]
        public List<Candidate> Candidates { get; set; } = new();

        public void OnGet()
        {
            Applicants = _service.ListJobApplicants();
            Openings = _service.ListJobOpenings();
        }

        public void OnPost()
        {
            // This info for the drop-downs 
            Openings = _service.ListJobOpenings();
        }
    }
}

src/Sandbox/WebApp/Pages/Secured/SpyAgency.cshtml.cs
using Backend.BLL;
using Backend.Models.SpyAgency;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Nager.Country;
using System.Collections.Generic;
using System.Linq;

namespace WebApp.Pages.Secured
{
    public class SpyAgencyModel : PageModel
    {
        private readonly SecretService _service;
        private readonly ILogger<SpyAgencyModel> _logger;
        public SpyAgencyModel(SecretService service, ILogger<SpyAgencyModel> logger)
        {
            _service = service;
            _logger = logger;
        }

        public List<Region> WorldRegions { get; set; }
        public List<SubRegion> SubRegions { get; set; }
        public List<ICountryInfo> Countries { get; set; }
        public Dictionary<string, List<Skill>> Agents { get; set; }
        public List<Assignment> Assignments
        { 
            get
            {
                var values = System.Enum.GetValues<Assignment>();
                return new List<Assignment>(values);
            }
        }
        public string WarningMessage { get; set; }
        [TempData]
        public string FeedbackMessage { get; set; }

        [BindProperty(SupportsGet = true)]
        public string RegionName { get; set; }
        [BindProperty(SupportsGet = true)]
        public SubRegion SubRegionName { get; set; }
        [BindProperty(SupportsGet =true)]
        public string CountryCode { get; set; }
        [BindProperty]
        public List<AgentAssignment> AgentAssignments { get; set; } = new List<AgentAssignment>(); // Ensure an empty list
        [BindProperty]
        public AgentAssignment NewlyAssignedAgent { get; set; }
        [BindProperty]
        public string AgentToRemove { get; set; }

        public void OnGet()
        {
            PopulateDropDownData();
            if(!string.IsNullOrEmpty(CountryCode))
                AgentAssignments = _service.LocateAgents(CountryCode);
        }

        private void PopulateDropDownData()
        {
            WorldRegions = _service.ListWorldRegions();
            SubRegions = _service.GetSubRegions(RegionName);
            Countries = SubRegionName == SubRegion.None ? new List<ICountryInfo>() : _service.GetCountries(SubRegionName);
            Agents = _service.AgentSkillSets;
        }

        public IActionResult OnPostChangeRegion()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = (string)null,
                CountryCode = (string)null
            });
        }

        public IActionResult OnPostChangeSubRegion()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = SubRegionName,
                CountryCode = (string)null
            });
        }

        public IActionResult OnPostChangeCountry()
        {
            return RedirectToPage(new
            {
                RegionName = RegionName,
                SubRegionName = SubRegionName,
                CountryCode = CountryCode
            });
        }

        public void OnPostAddAgent()
        {
            // Minimal UI validation
            // 1. Preventing duplicates
            if (AgentAssignments.Any(agent => agent.CodeName == NewlyAssignedAgent.CodeName))
            {
                WarningMessage = "You cannot add duplicate agents";
                _logger.LogInformation(WarningMessage);
            }
            else
                // UI Processing
                AgentAssignments.Add(NewlyAssignedAgent);

            PopulateDropDownData();

        }

        public void OnPostRemoveAgent()
        {
            var agent = AgentAssignments.FirstOrDefault(person => person.CodeName == AgentToRemove);
            if (agent != null)
                AgentAssignments.Remove(agent);
            else
                WarningMessage = $"Hmm. For some reason, {AgentToRemove} is already gone.";

            PopulateDropDownData();
        }

        public IActionResult OnPostAssignAgents()
        {
            try
            {
                _service.DeployAgents(CountryCode, AgentAssignments);
                FeedbackMessage = $"Agents have been deployed to {CountryCode}";
                return RedirectToPage(new { RegionName = "", SubRegionName = "", CountryCode = "" });
            }
            catch (System.Exception ex)
            {
                WarningMessage = ex.Message;
                return Page(); // so that I preserve the user's inputs so that they can correct any input
            }
        }

        public IActionResult OnPostClearForm()
        {
            return RedirectToPage(new {RegionName = "", SubRegionName = "", CountryCode = ""});
        }
    }
}

src/Sandbox/WebApp/Pages/UnderstandingModelBinding.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

namespace WebApp.Pages
{
    public class UnderstandingModelBindingModel : PageModel
    {
        public void OnGet()
        {
            IsGet = true;
        }

        [BindProperty]
        public Person Person { get; set; }

        public string PostHandler { get; set; }
        public bool IsGet { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime GraduationDate { get; set; }

        public void OnPostNormal()
        {
            CopyData(nameof(OnPostNormal));
        }

        public void OnPostPartialClear()
        {
            CopyData(nameof(OnPostPartialClear));
            Person.FirstName = null; // Clear just part of the person information
            ModelState.Clear(); // Without this, the change to Person.FirstName will not be applied when the page is rendered
        }

        public void OnPostFullClear()
        {
            CopyData(nameof(OnPostFullClear));
            Person = null; // Clear out the whole property object
            ModelState.Clear(); // Without this, the change to Person will not be applied when the page is rendered
        }

        private void CopyData(string handlerName)
        {
            PostHandler = handlerName;
            FirstName = Person.FirstName;
            LastName = Person.LastName;
            GraduationDate = Person.GraduationDate;
        }
    }

    public class Person
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime GraduationDate { get; set; }
    }
}

src/Sandbox/WebApp/Pages/About.cshtml
@page
@model WebApp.Pages.AboutModel
@{
    var db = Model.DatabaseVersion;
    var info = Model.DatabaseInfo;
}

<h1>About</h1>

<h2>Database Details</h2>

<p>The Capstone database version is <mark>@db.Version</mark>. The connection string is <code>@info.ConnectionString</code>.</p>

<h2>Web Server Details</h2>

<p>Static web files are located at <code>@Model.WebRootPath</code>. The application's root path is <code>@Model.ApplicationPath</code>.</p>

src/Sandbox/WebApp/Pages/AdHoc.cshtml
@page "{ClientId?}"
@model WebApp.Pages.AdHocModel
@{
}

<style>
    main {
        display: grid;
        grid-template-columns: 1.5fr 1fr;
    }
    main > h1, main > p {
        grid-column: span 2;
    }
</style>

<h1>Ad-Hoc</h1>

<p>A place for some random ideas and demonstrations.</p>

<section>
    <h3>Client Listing</h3>

    <table>
        <tr>
            <th>Confirmed</th>
            <th>Company Name</th>
        </tr>
        @foreach(var company in Model.Companies)
            {
                <tr>
                    <td>
                        @*@(company.Confirmed ? "Yes" : "")*@
                        <input type="checkbox" checked="@company.Confirmed" />
                    </td>
                    <td>
                        <a asp-area="" asp-page="/AdHoc" asp-route-ClientId="@company.Id">@company.CompanyName</a>
                    </td>
                </tr>
            }
    </table>
</section>

<section>
    <h3>Details</h3>
    @if (Model.Client != null)
    {
        <blockquote>
            The Client ID is @Model.Client.Id.
            @(Model.Client.Confirmed ? "Welcome Aboard!" : "Registration Pending")
        </blockquote>
    }

    <form method="post">
        <label>
            Company Name
            <input asp-for="Client.CompanyName" />
        </label>
        <label>
            Slogan
            <input asp-for="Client.Slogan" />
        </label>
        <label style="display: block;">
            Confirmation Status
            <br />
            <input asp-for="Client.Confirmed" /> Is Confirmed
        </label>
        <label>
            Contact Name
            <input asp-for="Client.ContactName" />
        </label>

        <button asp-page-handler="Add">Add</button>
        <button asp-page-handler="Update">Update</button>
        <button asp-page-handler="Delete">Delete</button>
        <button asp-page-handler="ClearForm">Clear Form</button>
    </form>
</section>

src/Sandbox/WebApp/Pages/ColorPalletPicker.cshtml
@page
@model WebApp.Pages.ColorPalletPickerModel
@{
}
<style>
    main>form {
        display: grid;
        grid-template-columns: 1fr 1fr;
    }
    .danger {
        color: var(--danger-text-color);
        background-color: var(--danger-color);
    }
    .danger:enabled:hover {
        background-color: var(--danger-hover-color);
        border-color: transparent;
    }
    th, td {
        white-space: nowrap;
    }
</style>

<form method="post">
    <div>
        <h1>Available Colors</h1>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Hex</th>
                    <th>RGB</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AvailableColors)
                {
                    <tr>
                        <td>
                            <input type="hidden" name="AvailableColors.Index" value="@item.Name" />
                            <button type="submit" name="SelectedColor" value="@item.Name" asp-page-handler="AddItem">Add</button>
                        </td>
                        <td>
                            <input type="hidden" name="AvailableColors[@item.Name].Name" value="@item.Name" />
                            <span style="display:inline-block; width: 16px; height: 16px; background-color:@item.HexCode"></span>
                            @item.Name
                        </td>
                        <td>
                            <input type="hidden" name="AvailableColors[@item.Name].HexCode" value="@item.HexCode" />
                            @item.HexCode
                        </td>
                        <td>
                            <input type="hidden" name="AvailableColors[@item.Name].RgbCode" value="@item.RgbCode" />
                            @item.RgbCode
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <div>
        <h1>Your Color Pallete</h1>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Hex</th>
                    <th>RGB</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ColorPallete)
                {
                    <tr>
                        <td>
                            <input type="hidden" name="ColorPallete.Index" value="@item.Name" />
                            <button type="submit" name="SelectedColor" value="@item.Name" asp-page-handler="RemoveItem" class="danger">Remove</button>
                        </td>
                        <td>
                            <input type="hidden" name="ColorPallete[@item.Name].Name" value="@item.Name" />
                            <span style="display:inline-block; width: 16px; height: 16px; background-color:@item.HexCode"></span>
                            @item.Name
                        </td>
                        <td>
                            <input type="hidden" name="ColorPallete[@item.Name].HexCode" value="@item.HexCode" />
                            @item.HexCode
                        </td>
                        <td>
                            <input type="hidden" name="ColorPallete[@item.Name].RgbCode" value="@item.RgbCode" />
                            @item.RgbCode
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</form>

src/Sandbox/WebApp/Pages/Contact.cshtml
@page
@model WebApp.Pages.ContactModel
@{
}

<h1>Contact Us</h1>

<form method="post" enctype="multipart/form-data">
    <label>Your Resume
        <input type="file" accept=".pdf" asp-for="ApplicantResume" />
    </label>
    <button type="submit">Upload File</button>
</form>

src/Sandbox/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Welcome</h1>
<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

src/Sandbox/WebApp/Pages/JobCandidates.cshtml
@page
@model WebApp.Pages.JobCandidatesModel
@{
}

<h1>Job Candidates</h1>

<form method="post">
    <label>
        Job Position
        <select>
            <option asp-for="SelectedOpening">Select a Job</option>
            @foreach (var job in Model.Openings)
            {
                <option selected="@(job == Model.SelectedOpening)">@job</option>
            }
        </select>
    </label>
    <button type="submit">Shortlist</button>
    <table>
        <thead>
            <tr>
                <th>✔</th>
                <th>Name</th>
                <th>Interview Date</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var person in Model.Applicants)
            {
                var candidate = Model.Candidates.SingleOrDefault(x => x.Id == person.Id);
                var interviewDate = candidate != null && candidate.InterviewDate.HasValue
                                  ? candidate.InterviewDate.Value.ToString("yyyy-MM-dd")
                                  :  ""; // simplifies 
                var notes = candidate != null ? candidate.Notes : "";
                <tr>
                    <td>
                        <input type="hidden" name="Candidates.Index" value="@person.Id" />
                        <input type="hidden" name="Candidates[@person.Id].Id" value="@person.Id" />
                        <input type="checkbox" name="Candidates[@person.Id].ShortList" checked="@candidate?.ShortList" value="true"  />
                    </td>
                    <td>
                        <input type="hidden" name="Applicants.Index" value="@person.Id" />
                        <input type="hidden" name="Applicants[@person.Id].Id" value="@person.Id" />
                        <input type="hidden" name="Applicants[@person.Id].FirstName" value="@person.FirstName" />
                        <input type="hidden" name="Applicants[@person.Id].LastName" value="@person.LastName" />
                        @person.FirstName <b>@person.LastName</b>
                    </td>
                    <td>
                        <input type="date" name="Candidates[@person.Id].InterviewDate"
                            value="@interviewDate"/>
                    </td>
                    <td>
                        <textarea style="min-height:auto" rows="2" name="Candidates[@person.Id].Notes">@notes</textarea>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

src/Sandbox/WebApp/Pages/UnderstandingModelBinding.cshtml
@page
@model WebApp.Pages.UnderstandingModelBindingModel
@{
}

<style>
    form{
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 15px;
    }
</style>
<form method="post">
    <label asp-for="Person.FirstName">Two-Way Binding</label>
    <label asp-for="Person.LastName">Two-Way Binding</label>
    <label asp-for="Person.GraduationDate">One-Way Binding</label>

    <input asp-for="Person.FirstName" placeholder="First Name" autofocus />
    <input asp-for="Person.LastName" placeholder="Last Name" />
    <input type="date" name="Person.GraduationDate" placeholder="Graduation Date" />

    <button type="submit" asp-page-handler="PartialClear"><b>Partial Clear</b></button>
    <button type="submit" asp-page-handler="FullClear"><b>Full Clear</b></button>
    <button type="submit" asp-page-handler="Normal"><b>Normal</b></button>
</form>

    @if(!Model.IsGet)
    {
<blockquote>
        (@Model.PostHandler) - 
        <b>@Model.FirstName</b> <b>@Model.LastName</b>
        Graduated on <b>@Model.GraduationDate.ToShortDateString()</b>
</blockquote>
    }

src/Sandbox/WebApp/Pages/ViewCapstoneStudents.cshtml
@page
@model WebApp.Pages.ViewCapstoneStudentsModel
@{
}

<h1>Capstone Students</h1>

<p>Students in Capstone will be assigned to specific teams that work with a client to deliver a specific software product.</p>

<blockquote>
    <form method="get">
        <label>
            Partial Student Name
            <input type="text" asp-for="PartialStudentName" placeholder="leave blank for all students" />
        </label>
        <button type="submit">Filter</button>
    </form>
</blockquote>

<table>
    <thead>
        <tr>
            <th>Student</th>
            <th>Team</th>
            <th>Client</th>
            <th>Confirmed</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model.StudentAssignments)
        {
            var status = student.Assignment != null
                       ? (student.Assignment.IsConfirmed ? "Confirmed" : "Temporary")
                       : "Unassigned";
            <tr>
                <td>@student.FirstName @student.LastName</td>
                <td>@student.Assignment?.Number</td>
                <td>@student.Assignment?.Client</td>
                <td>
                    @status
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr colspan="4">
            <td>
                @{
                    foreach (var pageRef in Model.Paging)
                    {
                        if (pageRef == Model.Paging.CurrentPage) // I can use the == because of PageRef type being a C# 9 record type
                        {
                            <b>@pageRef.Text</b>
                        }
                        else
                        {
                            <a title="Page @pageRef.Page"
                               asp-page="/ViewCapstoneStudents"
                               asp-route-currentpage="@pageRef.Page"
                               asp-route-PartialStudentName="@Model.PartialStudentName">@pageRef.Text</a>
                        }
                    }
                }
                (@Model.Paging.TotalItemCount items - Page x/@Model.Paging.PageCount)
            </td>
        </tr>
    </tfoot>
</table>