src/WestWind/WebApp/Pages/Admin/Database/ManageShippers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WestWind.App.BLL;
using WestWind.App.Models.CRUD;

namespace WebApp.Pages.Admin.Database
{
    // ![](../../Design/ManageShippers.png)
    public class ManageShippersModel : PageModel
    {
        #region Constructor and Depedencies
        private readonly ShippingService _service;
        public ManageShippersModel(ShippingService service)
        {
            _service = service;
        }
        #endregion

        #region Properties
        public List<Shipper> CurrentShippers { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? SelectedShipperId { get; set; }
        [BindProperty]
        public Shipper ShipperData { get; set; }

        [TempData]
        public string UserFeedback { get; set; }
        public string ErrorMessage { get; set; }
        public bool HasError => !string.IsNullOrWhiteSpace(ErrorMessage);
        public bool HasFeedback => !string.IsNullOrWhiteSpace(UserFeedback);
        #endregion

        #region GET/POST Handlers
        public void OnGet()
        {
            CurrentShippers = _service.ListShippers();
        }

        #region POST Handlers
        public IActionResult OnPost()
        {
            // This action handler will be for getting into an "edit mode"
            UserFeedback = $"Edit mode for shipper {SelectedShipperId}.";
            return RedirectToPage(new { SelectedShipperId });
        }

        public IActionResult OnPostCancel()
        {
            UserFeedback = "Cancel operation.";
            return RedirectToPage(new { SelectedShipperId = (int?)null });
        }

        public IActionResult OnPostUpdate()
        {
            try
            {
                _service.UpdateShipper(ShipperData);
                UserFeedback = $"Updated shipper information for {ShipperData.ID} ({ShipperData.CompanyName} - {ShipperData.Phone}).";
                return RedirectToPage(new { SelectedShipperId = ShipperData.ID });
            }
            catch (Exception ex)
            {
                return HandleCRUDError(ex);
            }
        }

        public IActionResult OnPostInsert()
        {
            try
            {
                _service.AddShipper(ShipperData);
                UserFeedback = $"New shipper information added ({ShipperData.CompanyName} - {ShipperData.Phone}).";
                return RedirectToPage(new { SelectedShipperId = (int?)null });
            }
            catch (Exception ex)
            {
                return HandleCRUDError(ex);
            }
        }

        public IActionResult OnPostDelete()
        {
            try
            {
                _service.DeleteShipper(SelectedShipperId.Value);
                UserFeedback = $"Remove shipper {SelectedShipperId}.";
                return RedirectToPage(new { SelectedShipperId = (int?)null });
            }
            catch (Exception ex)
            {
                return HandleCRUDError(ex);
            }
        }
        #endregion
        #endregion

        #region Private Helper Methods
        private IActionResult HandleCRUDError(Exception ex)
        {
            // Get to the root of the problem
            ReportError(ex);

            // Populate the list of shippers
            CurrentShippers = _service.ListShippers();

            // Return this page POST processing results
            return Page();
        }

        private void ReportError(Exception ex)
        {
            Exception innermost = ex;
            while (innermost.InnerException != null)
                innermost = innermost.InnerException;
            ErrorMessage = innermost.Message;
        }
        #endregion
    }
}

src/WestWind/WebApp/Pages/Admin/Database/ManageShippers.cshtml
@page "{SelectedShipperId?}"
@model WebApp.Pages.Admin.Database.ManageShippersModel
@{
}

@*![](../../Design/ManageShippers.png)*@

<h1>Manage Shippers</h1>

<form method="post" id="editForm"></form>

@if (Model.HasFeedback)
{
    <blockquote class="success">@Model.UserFeedback</blockquote>
}
@if (Model.HasError)
{
    <blockquote class="error">@Model.ErrorMessage</blockquote>
}

<table>
    <thead>
        <tr>
            <th>Action</th>
            <th>Company Name</th>
            <th>Phone</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var company in Model.CurrentShippers)
        {
            <tr>
                <td>
                    @if (Model.SelectedShipperId.HasValue && Model.SelectedShipperId.Value == company.ID)
                    {
                        // Edit Mode
                        <text>
                            <button type="submit" form="editForm" asp-page-handler="Update"><i class="las la-check"></i></button>
                            <button type="submit" form="editForm" asp-page-handler="Cancel" formnovalidate><i class="las la-times"></i></button>
                            <input type="hidden" asp-for="ShipperData.ID" value="@company.ID" form="editForm" />
                        </text>
                    }
                    else
                    {
                        // View Mode
                        <form method="post">
                            <input type="hidden" asp-for="SelectedShipperId" value="@company.ID" />
                            <button type="submit" title="Edit this shipper"><i class="las la-pencil-alt"></i></button>
                            <button type="submit" title="Delete this shipper" onclick="return confirm('Are you sure you want to delete this shipper?');" asp-page-handler="Delete"><i class="lar la-trash-alt"></i></button>
                        </form>
                    }
                </td>
                <td>
                    @if (Model.SelectedShipperId.HasValue && Model.SelectedShipperId.Value == company.ID)
                    {
                        <input type="text" form="editForm" asp-for="ShipperData.CompanyName" value="@company.CompanyName" />
                    }
                    else
                    {
                        @: @company.CompanyName
                    }
                </td>
                <td>
                    @if (Model.SelectedShipperId.HasValue && Model.SelectedShipperId.Value == company.ID)
                    {
                        <input type="text" form="editForm" asp-for="ShipperData.Phone" value="@company.Phone" />
                    }
                    else
                    {
                        @: @company.Phone
                    }
                </td>
            </tr>
        }
    </tbody>
    @if (!Model.SelectedShipperId.HasValue)
    {
        <tfoot>
            <tr>
                <td>
                    <text>
                        <button type="submit" form="editForm" asp-page-handler="Insert"><i class="las la-plus"></i></button>
                        <button type="submit" form="editForm" asp-page-handler="Cancel" formnovalidate><i class="las la-times"></i></button>
                    </text>
                </td>
                <td>
                    <input type="text" form="editForm" asp-for="ShipperData.CompanyName" placeholder="Company Name" />
                </td>
                <td>
                    <input type="text" form="editForm" asp-for="ShipperData.Phone" placeholder="Phone (###) ###-####" />
                </td>
            </tr>
        </tfoot>
    }
</table>

src/WestWind/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Welcome</h1>
<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

src/WestWind/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a asp-area="" asp-page="/Index">WebApp</a></li>
                <li><a asp-area="" asp-page="/Index">Home</a></li>
                <li><a asp-area="" asp-page="/Privacy">Privacy</a></li>
                <li>Admin
                    <ul>
                        <li>
                            <a asp-area="" 
                               asp-page="/Admin/Database/ManageShippers" 
                               asp-route-SelectedShipperId="">Manage Shippers</a>
                        </li>
                    </ul>
                </li>
                <partial name="_LoginPartial" />
            </ul>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>

    <footer>
        <div>
            &copy; 2021 - WebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>